# parameters
ARG REPO_NAME="assignment3"
ARG DESCRIPTION="PA3 maze navigation with A* and AprilTag localization"
ARG MAINTAINER="Student <student@duckietown.org>"
ARG ICON="map"

# ==================================================>
# ==> Do not change the code below this line
ARG ARCH
ARG DISTRO=daffy
ARG DOCKER_REGISTRY=docker.io
ARG BASE_IMAGE=dt-ros-commons
ARG BASE_TAG=${DISTRO}-${ARCH}
ARG LAUNCHER=default

FROM ${DOCKER_REGISTRY}/duckietown/${BASE_IMAGE}:${BASE_TAG} as base

ARG DISTRO
ARG REPO_NAME
ARG DESCRIPTION
ARG MAINTAINER
ARG ICON
ARG BASE_TAG
ARG BASE_IMAGE
ARG LAUNCHER
ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT

RUN dt-build-env-check "${REPO_NAME}" "${MAINTAINER}" "${DESCRIPTION}"

ARG REPO_PATH="${CATKIN_WS_DIR}/src/${REPO_NAME}"
ARG LAUNCH_PATH="${LAUNCH_DIR}/${REPO_NAME}"
RUN mkdir -p "${REPO_PATH}" "${LAUNCH_PATH}"
WORKDIR "${REPO_PATH}"

ENV DT_MODULE_TYPE="${REPO_NAME}" \
 DT_MODULE_DESCRIPTION="${DESCRIPTION}" \
    DT_MODULE_ICON="${ICON}" \
    DT_MAINTAINER="${MAINTAINER}" \
    DT_REPO_PATH="${REPO_PATH}" \
    DT_LAUNCH_PATH="${LAUNCH_PATH}" \
    DT_LAUNCHER="${LAUNCHER}"

COPY ./dependencies-apt.txt "${REPO_PATH}/"
RUN dt-apt-install ${REPO_PATH}/dependencies-apt.txt

ARG PIP_INDEX_URL="https://pypi.org/simple"
ENV PIP_INDEX_URL=${PIP_INDEX_URL}
COPY ./dependencies-py3.* "${REPO_PATH}/"
RUN dt-pip3-install "${REPO_PATH}/dependencies-py3.*"

COPY ./packages "${REPO_PATH}/packages"

RUN . /opt/ros/${ROS_DISTRO}/setup.sh && \
    catkin build \
    --workspace ${CATKIN_WS_DIR}/

COPY ./launchers/. "${LAUNCH_PATH}/"
RUN dt-install-launchers "${LAUNCH_PATH}"

CMD ["bash", "-c", "dt-launcher-${DT_LAUNCHER}"]

LABEL org.duckietown.label.module.type="${REPO_NAME}" \
      org.duckietown.label.module.description="${DESCRIPTION}" \
      org.duckietown.label.module.icon="${ICON}" \
      org.duckietown.label.platform.os="${TARGETOS}" \
      org.duckietown.label.platform.architecture="${TARGETARCH}" \
      org.duckietown.label.platform.variant="${TARGETVARIANT}" \
      org.duckietown.label.code.location="${REPO_PATH}" \
      org.duckietown.label.code.version.distro="${DISTRO}" \
      org.duckietown.label.base.image="${BASE_IMAGE}" \
      org.duckietown.label.base.tag="${BASE_TAG}" \
      org.duckietown.label.maintainer="${MAINTAINER}"
# <== Do not change the code above this line
# <==================================================
